### ISSUE TITLE
Add reference to this repo in Easy Random's home page

### ISSUE THREAD

**Issue by fmbenhassine** [xShadov/easy-random-vavr-extension#1]
Hi @xShadov,

Sorry for opening this issue, I could not find another way to contact you.

I came across this repo and find it awesome! May I ask for your permission to add a reference to it here: https://github.com/j-easy/easy-random#extensions ?

Thank you for using Easy Random and for creating this extension!

Best regards,
Mahmoud

**Comment by fmbenhassine** [comment]
As Grace Hopper said: "It's easier to ask forgiveness than it is to get permission".

So I added a reference to this extension to the home page: https://github.com/j-easy/easy-random/blob/master/README.md#extensions and please forgive me if I should not have done that. If you disagree, let me know and I will remove it.

Thank you for using Easy Random and for creating this extension!

**Comment by xShadov** [comment]
Sorry for missing that, I have been quite busy recently. Why are there no normal private messages on Github?:)

I wrote you an e-mail about this extension last september asking some questions about implementation and other possible features. 

Of course you can add it to the home page (or rather keep it than add it at this point), but I'm afraid it's not gonna help much people now, since it's not published. I will work on publishing it on maven central, never done that before, but it can't be that hard :)
